### ISSUE TITLE
about nonce byte array

### ISSUE THREAD

**Issue by yooyo** [robmuth/eth-ac-verifier#1]
hello,i meet some question when i Reproduce your work. i ues generate_nonce() in anoncreds.py to generate nonce used for credential verification. I learned nonce is 80-bit number, but nonce generated from generate_nonce() is 24bytes.I want know how can i generate nonce like nonce in your code is []byte and size is 10? hope your help,thanks.

**Comment by robmuth** [comment]
Hi Yooyo,

That's interesting. I haven't used anoncreds.py before, so it's hard for me to answer your question right away.

First, the nonce must be 80 bits in length according to the Hyperledger Anoncreds specification (see [here](https://hyperledger.github.io/anoncreds-spec/#create-presentation-request)). That is also why I've put the [requirement-check](https://github.com/robmuth/eth-ac-verifier/blob/main/contracts/Verify.sol#L587) at the beginning of the verify method.

After a quick look at the anoncreds.py implementation, I would actually expect it to return an 80-bit nonce, as you can see [here](https://github.com/hyperledger/indy-sdk/blob/83547c4c01162f6323cf138f8b071da2e15f0c90/wrappers/python/indy/anoncreds.py#L1884). So I'm wondering where the 24 bytes you mention come from. Perhaps I can help you if you provide more details. Could it be a data type issue (e.g., casting/converting a string to bytes?). But (again) I'm not an expert for the anoncreds.py implementation...

**Comment by yooyo** [comment]
> 
Hello,Rob!
I am glad to receive your reply, now I will introduce my problem.
First, I add print(len(nonce)) in generate_nonce()  , when I invoke anoncred.generate_nonce() ,I find the print out is 24,so I think the nonce is 24bytes.
the generate_nonce() function is:
async def generate_nonce() -> str:
    """
    Generates 80-bit numbers that can be used as a nonce for proof request.

    :return: nonce: generated number as a string
    """

    logger = logging.getLogger(__name__)
    logger.debug("generate_nonce: >>>")

    if not hasattr(generate_nonce, "cb"):
        logger.debug("generate_nonce: Creating callback")
        generate_nonce.cb = create_cb(CFUNCTYPE(None, c_int32, c_int32, c_char_p))

    nonce = await do_call('indy_generate_nonce',
                          generate_nonce.cb)
    print('nonce',nonce)
    print('nonce_len',len(nonce))
    print('nonce',nonce.hex())
    
    res = nonce.decode()
    logger.debug("generate_nonce: <<< res: %r", res)
    return res
And print out is :
nonce b'875801454675205869364769'
nonce_len 24
nonce 383735383031343534363735323035383639333634373639
So I'm confused very much.
I agree maybe the problem is about data type,so I what to get your nonce(string or []byte) in  construct proof_request, thank you very much~

**Comment by robmuth** [comment]
Ah I see, no worries. So, the nonce is shown as a decimal number ($875801454675205869364769$) but it is 80 bits longs. When you print the nonce as hex string, you get the 10 bytes: 

```
print(str(hex(nonce)))
> 0xb9754abff01f82c96621
```

**Comment by yooyo** [comment]
> Ah I see, no worries. So, the nonce is shown as a decimal number (875801454675205869364769) but it is 80 bits longs. When you print the nonce as hex string, you get the 10 bytes:
> 
> ```
> print(str(hex(nonce)))
> > 0xb9754abff01f82c96621
> ```

oh,yes!Thanks for your answer. And when nonce is  0xb9754abff01f82c96621 ,I want to know how nonce byte array is？in your project test code,test_verify.js.
nonce : [0xb9, 0x75, 0x4a, 0xbf, 0xf0, 0x1f, 0x82, 0xc9, 0x66, 0x21] or 
nonce : [0x21, 0x66, 0xc9, 0x82, 0x1f, 0xf0, 0xbf, 0xc4a, 0x75, 0xb9] ?

**Comment by yooyo** [comment]
> Ah I see, no worries. So, the nonce is shown as a decimal number (875801454675205869364769) but it is 80 bits longs. When you print the nonce as hex string, you get the 10 bytes:
> 
> ```
> print(str(hex(nonce)))
> > 0xb9754abff01f82c96621
> ```

oh,yes!thanks dor your answer. And when nonce is  0xb9754abff01f82c96621 ,I want to know how nonce byte array is？in your project test code,test_verify.js.
nonce : [0xb9, 0x75, 0x4a, 0xbf, 0xf0, 0x1f, 0x82, 0xc9, 0x66, 0x21] or 
nonce : [0x21, 0x66, 0xc9, 0x82, 0x1f, 0xf0, 0xbf, 0xc4a, 0x75, 0xb9] ?

**Comment by robmuth** [comment]
It should be big-endian. So ```[0xb9, 0x75, 0x4a, 0xbf, 0xf0, 0x1f, 0x82, 0xc9, 0x66, 0x21]``` would be the right one.

**Comment by yooyo** [comment]
Thank you very much,by the way,Have you considered smart contract verication about revocation?

**Comment by robmuth** [comment]
You are very welcome. For now, we don't plan to continue working on the revocation, as we've started investigating more practical verification techniques (e.g., with [Zokrates](https://github.com/JonathanHeiss/ZoKrates-Credential-Verification)).
